# Generated by Django 4.2.9 on 2024-01-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("datetime", models.DateField()),
                ("done_task_until_date", models.DateField(blank=True)),
                ("task_is_done", models.BooleanField()),
                ("tags", models.ManyToManyField(to="task_and_tags.tag")),
            ],
            options={
                "ordering": ["task_is_done"],
            },
        ),
    ]
